name: Debug

on:
  push:
    branches: [ master , develop*]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master , develop*]
    paths-ignore:
      - '**/README.md'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageDebugUniversalApk
    - name: Get app version
      run: echo "APP_VERSION=v$(cat ./app/build.gradle | grep -m1 versionName | awk -F \" '{print $2}')" >> $GITHUB_ENV
    - name: Get app name
      run: echo "APP_NAME=LinkToApk-DEBUG#${{ github.run_number }}" >> $GITHUB_ENV
    - name: Rename the APK file
      run: mv ./app/build/outputs/universal_apk/debug/app-debug-universal.apk ./${{ env.APP_NAME }}.apk
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.APP_NAME }}
        path: ./${{ env.APP_NAME }}.apk

